Identifying missing values in tabular
import pandas as pd
from io import StringIO
import sys
csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''
# If you are using Python 2.7, you need
# to convert the string to unicode:
if (sys.version_info < (3, 0)):
    csv_data = unicode(csv_data)

Step 1: Read the csv file as a pandas dataframe


In [7]:
import pandas as pd
from io import StringIO
import sys

csv_data = \
'''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''
if (sys.version_info < (3,0)):
  csv_data = unicode(csv_data)
df= pd.read_csv(StringIO(csv_data))
df

A     B     C   D 
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

Step 2: Check the number of missing values for the columns


In [8]:
df.isnull()

A      B      C     D 
0  False  False  False  False
1  False  False   True  False
2  False  False  False   True

Step 3: access the underlying NumPy array via the values attribute


In [9]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

Step 4: Remove rows from df that contain missing values


In [10]:
df.dropna(axis=0)

A    B    C   D 
0  1.0  2.0  3.0  4.0

Step 5: Remove columns from df that contain missing values


In [11]:
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

Step 6: Only drop rows where all columns are NaN


In [12]:
df.dropna(how='all')

A     B     C   D 
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

Step 7: Drop rows that have less than 3 real values


In [13]:
df.dropna(thresh=4)

A    B    C   D 
0  1.0  2.0  3.0  4.0

Step 8: Only drop rows where NaN appear in specific columns (here: 'C')


In [14]:
df.dropna(subset='C',axis=0)

A     B     C   D 
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

Imputing missing values
# again: our original array
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

impute missing values via the column mean

In [16]:
from sklearn.impute import SimpleImputer
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])